language: c
dist: trusty
sudo: false

os:
  - linux
  # Re-enable MacOS builds when travis-ci Mac OS build queues improve
  # - osx

compiler:
  - clang
  - gcc

install:
  - git clone https://github.com/polysat/polyxdr ~/polyxdr
  - cd ~/polyxdr
  - sudo python3 setup.py install
  - source ~/.bashrc
  - cd ~/Polysat/libproc

script: make
