#!/usr/bin/env python3
import os
import sys
import argparse
import pyparsing
import importlib
from xdr.parser import *

def main():
    parser = argparse.ArgumentParser(description='XDR compiler')
    parser.add_argument("input", metavar="FILE", type=argparse.FileType('r'), help="Input file")
    parser.add_argument("--target", "-t", required=True, choices=["python", "xp","libproc"], help="Target language")
    parser.add_argument("--output", "-o", metavar="PATH", help="Output directory")

    args = parser.parse_args()

    if args.output:
        output = args.output
    else:
        output = os.path.basename(args.input.name) + "." + args.target

    try:
        p = Parser(args.input.name, None)
        ir = p.xdr_parse(args.input.read())
    except pyparsing.ParseSyntaxException as e:
        sys.exit("Parsing failed: %s at %s line %d col %d" % (e.msg, args.input.name, e.lineno, e.col))

    try:
        backend = importlib.import_module("xdr.backends." + args.target)
        backend.generate(ir, output)
    except ImportError as e:
        print(e)
        sys.exit("The target %r is not supported" % args.target)


if __name__ == "__main__" :
    main()
